#!/bin/bash
# DON'T REMOVE FROM test script.
CYAN='\033[0;36m'
BCYAN='\033[1;36m'
NC='\033[0m' # No Color
DIVIDER="********************************************************************************\n"

function get_project_id() {
    local __resultvar=$1
    VALUE=$(gcloud config get-value project | xargs)
    eval $__resultvar="'$VALUE'"
}

function get_project_number() {
    local __resultvar=$1
    local PRO=$2
    VALUE=$(gcloud projects list --filter="project_id=$PRO" --format="value(PROJECT_NUMBER)" | xargs)
    eval $__resultvar="'$VALUE'"
}

# DISPLAY HELPERS
function section_open() {
    section_description=$1
    printf "$DIVIDER"
    printf "${CYAN}$section_description${NC} \n"
    printf "$DIVIDER"
}

function section_close() {
    printf "$DIVIDER"
    printf "${CYAN}$section_description ${BCYAN}- done${NC}\n"
    printf "\n\n"
}

function evalTest() {
    local command=$1
    local expected=$2

    local ERR=""
    got=$(eval $command 2>errFile)
    ERR=$(<errFile)

    if [ ${#ERR} -gt 0 ]; then
        if [ "$expected" = "EXPECTERROR" ]; then
            printf "Expected Error thrown \n"
            return
        fi

        printf "Halting - error: '$ERR'  \n"
        exit 1
    fi

    if [ "$got" != "$expected" ]; then
        printf "Halting: '$got'  \n"
        exit 1
    fi

    printf "$expected is ok\n"
}

# END DON'T REMOVE FROM test script.

DOMAIN=$APPINABOX_YESORNOSITE_DOMAIN
get_project_id PROJECT
get_project_number PROJECT_NUMBER "$PROJECT"

BUCKET=$DOMAIN
BASENAME=${DOMAIN//./-}
CLOUDDNSZONE=$BASENAME-zone



section_open "Delete DNS Records"
    gcloud dns record-sets delete "$DOMAIN" --zone "$CLOUDDNSZONE" --type A -q 
    gcloud dns managed-zones delete "$BASENAME"-zone -q 
section_close

section_open "Delete the IP Address"
    gcloud compute addresses delete "$BASENAME"-ip --global -q
section_close

section_open "Delete the Cloud Storage Bucket"
    gcloud storage rm --recursive --continue-on-error gs://"$DOMAIN" 
section_close



section_open "Delete Load Balancer"
    gcloud compute forwarding-rules delete "$BASENAME"-https-lb-forwarding-rule --global -q 
    gcloud compute target-https-proxies delete "$BASENAME"-ssl-lb-proxy --global -q 
    gcloud compute forwarding-rules delete  "$BASENAME"-http-lb-forwarding-rule --global -q 
    gcloud compute target-http-proxies delete "$BASENAME"-lb-proxy  --global -q 
    gcloud compute url-maps delete "$BASENAME"-lb --global -q 
    gcloud compute backend-buckets delete  "$BASENAME"-be -q 
section_close

section_open "Delete SSL cert"
    gcloud compute ssl-certificates delete "$BASENAME"-cert -q
section_close
